"""user table migration

Revision ID: 923ff3efe757
Revises: 8c48280d4b4a
Create Date: 2020-12-27 22:04:28.086587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '923ff3efe757'
down_revision = '8c48280d4b4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line_1', sa.String(), nullable=True),
    sa.Column('address_line_2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('birthday', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('community_id', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('registerTime', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('user_image', sa.String(), nullable=True))
    op.add_column('user', sa.Column('username', sa.String(), nullable=True))
    op.add_column('user', sa.Column('validate_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'validate_status')
    op.drop_column('user', 'username')
    op.drop_column('user', 'user_image')
    op.drop_column('user', 'registerTime')
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'is_admin')
    op.drop_column('user', 'email')
    op.drop_column('user', 'community_id')
    op.drop_column('user', 'birthday')
    op.drop_table('transaction')
    op.drop_table('address')
    # ### end Alembic commands ###
