# Generated by Django 3.1.4 on 2020-12-28 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
