# Generated by Django 3.1.4 on 2020-12-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0002_customuser_validate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='#($=gtmv(g3ji@u2y442', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_time',
            field=models.DateTimeField(null=True),
        ),
    ]
