# Generated by Django 3.1.4 on 2020-12-28 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0003_auto_20201228_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reframery.address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reframery.community'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='by5we59hi8dh*0iw3&1m', max_length=255),
        ),
    ]
