# Generated by Django 3.1.4 on 2020-12-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0004_auto_20201228_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='nfc%!2%chwc-pk0fs6rl', max_length=255),
        ),
    ]
