# Generated by Django 3.1.4 on 2020-12-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0005_auto_20201228_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='-2)r+im@&6)ne&+ruuly', max_length=255),
        ),
    ]
