# Generated by Django 3.1.4 on 2020-12-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0007_auto_20201228_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='mou=ro0qtn-9x*ffx)+&', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_status',
            field=models.BooleanField(default=False),
        ),
    ]
