# Generated by Django 3.1.4 on 2020-12-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0008_auto_20201229_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='3euf#_l0=-&&u&obs1gi', max_length=255),
        ),
    ]
