# Generated by Django 3.1.5 on 2021-02-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0010_auto_20201229_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('customUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reframery.customuser')),
                ('address', models.CharField(max_length=255)),
                ('private_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='kvvajs2cb3imbj#!4ycl', max_length=255),
        ),
    ]
