# Generated by Django 3.1.5 on 2021-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0011_auto_20210222_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='mszrr98-o#tp1^8&j-4h', max_length=255),
        ),
    ]
