# Generated by Django 3.1.5 on 2021-04-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reframery', '0012_auto_20210401_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validate_code',
            field=models.CharField(default='yn&+*e6vt-+ux24c(dlk', max_length=255),
        ),
    ]
